# COGS180 Final Project: AI Use and Rationality

In [298]:
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
import plotly.io as pio

In [299]:
survey_data = pd.read_csv('/Users/nicolechen/COGS 180/AI Use Survey Responses (n=65).csv')

In [300]:
survey_data.shape

(65, 29)

In [301]:
survey_data.head()

,Timestamp,What year of college are you in?,What is your major?,How often do you use AI/LLM tools?,What domains do you use AI in?,What (if any) rules or expectations affect your decision to use AI?,I primarily think of LLMs as a:,How would you classify your “AI-use personality”?,What environments do you feel AI use is most justified in?,What was your most recent AI prompt?,...,Using AI improved the quality of my final outcome.,Using AI helped me think more clearly about the problem.,"Using AI required additional effort (e.g., prompting, correcting, fact-checking).","In this situation, using AI felt like the most rational choice.",What AI/LLM did you use? (please specify if other),"Regarding your answer above, how familiar were you with the AI tool you used?","Regarding the previous question, why did you choose to use this AI/LLM?","If given the choice again for a similar task, I would:",What conditions need to be present for you to feel confident that using AI is the “right” choice?,Can you describe a time when using AI actually made the task harder or more time-consuming?
0,2/20/2026 11:46:34,Senior,ESYS,A few times a year,Schoolwork / Studying,"Environmental concerns, Ethical concerns",Brainstorming partner,"Cautious user (uses occasionally, as a last re...",Learning new skills,help formatting a poster,...,5,4,2,4,ChatGPT,5,most familiar,Probably use AI,NaN,NaN
1,2/20/2026 11:48:12,First-year transfer,Data Science,Multiple times a week,"Schoolwork / Studying, Creative projects, Codi...","Ethical concerns, Fear of academic / professio...","Tool for repetitive or menial tasks, Coding as...",Generous adopter (uses daily but is cautious a...,"Learning new skills, High-pressure deadlines, ...",“What is the parameter S in the context of the...,...,4,5,5,5,ChatGPT,5,Paid subscription and already tweaked to perso...,Probably use AI,Don’t have AI do something you don’t already h...,Trying to make large refactors in coding proje...
2,2/20/2026 11:53:19,Junior,Cognitive Science (spec. ML),Daily,"Schoolwork / Studying, Career / Professional t...","Workplace policies, Social norms, Ethical conc...","Replacement for Google / search engines, Tool ...",Generous adopter (uses daily but is cautious a...,"High-pressure deadlines, Low-stakes exploratio...",give me the rundown on ibm watsonx for gen ai ...,...,3,3,3,4,ChatGPT,5,I am used to it,Unsure,NaN,erm front-end web dev and css copilot suuuuuuc...
3,2/20/2026 13:15:02,Sophomore,ICAM/Cogsci,Multiple times a day,"Schoolwork / Studying, Career / Professional t...","All of the above, but they unfortunately fail ...","Tool for repetitive or menial tasks, Coding as...",Overuser / Devoted User (uses LLMs in most dom...,"Learning new skills, High-pressure deadlines, ...",(asking about athletic shirt details based on ...,...,4,4,2,4,ChatGPT,5,"Found it easier to prompt compared to Gemini, ...",Probably use AI,NaN,One example is when trying to improve image qu...
4,2/20/2026 14:20:33,Second-year transfer,Cognitive Science Design Spec,Never,NaN,"Environmental concerns, Ethical concerns, Conc...",General thinking assistant,AI skeptic (rarely or never uses LLMs),Actually useful tasks such as ML for cancer de...,Generating an image of a website low-fi wireframe,...,1,1,5,1,ChatGPT,1,Forced to by my professor as part of an assign...,Definitely not use AI,If the past three or so years of AI developmen...,Every single time

In [302]:
survey_data.head()

,Timestamp,What year of college are you in?,What is your major?,How often do you use AI/LLM tools?,What domains do you use AI in?,What (if any) rules or expectations affect your decision to use AI?,I primarily think of LLMs as a:,How would you classify your “AI-use personality”?,What environments do you feel AI use is most justified in?,What was your most recent AI prompt?,...,Using AI improved the quality of my final outcome.,Using AI helped me think more clearly about the problem.,"Using AI required additional effort (e.g., prompting, correcting, fact-checking).","In this situation, using AI felt like the most rational choice.",What AI/LLM did you use? (please specify if other),"Regarding your answer above, how familiar were you with the AI tool you used?","Regarding the previous question, why did you choose to use this AI/LLM?","If given the choice again for a similar task, I would:",What conditions need to be present for you to feel confident that using AI is the “right” choice?,Can you describe a time when using AI actually made the task harder or more time-consuming?
0,2/20/2026 11:46:34,Senior,ESYS,A few times a year,Schoolwork / Studying,"Environmental concerns, Ethical concerns",Brainstorming partner,"Cautious user (uses occasionally, as a last re...",Learning new skills,help formatting a poster,...,5,4,2,4,ChatGPT,5,most familiar,Probably use AI,NaN,NaN
1,2/20/2026 11:48:12,First-year transfer,Data Science,Multiple times a week,"Schoolwork / Studying, Creative projects, Codi...","Ethical concerns, Fear of academic / professio...","Tool for repetitive or menial tasks, Coding as...",Generous adopter (uses daily but is cautious a...,"Learning new skills, High-pressure deadlines, ...",“What is the parameter S in the context of the...,...,4,5,5,5,ChatGPT,5,Paid subscription and already tweaked to perso...,Probably use AI,Don’t have AI do something you don’t already h...,Trying to make large refactors in coding proje...
2,2/20/2026 11:53:19,Junior,Cognitive Science (spec. ML),Daily,"Schoolwork / Studying, Career / Professional t...","Workplace policies, Social norms, Ethical conc...","Replacement for Google / search engines, Tool ...",Generous adopter (uses daily but is cautious a...,"High-pressure deadlines, Low-stakes exploratio...",give me the rundown on ibm watsonx for gen ai ...,...,3,3,3,4,ChatGPT,5,I am used to it,Unsure,NaN,erm front-end web dev and css copilot suuuuuuc...
3,2/20/2026 13:15:02,Sophomore,ICAM/Cogsci,Multiple times a day,"Schoolwork / Studying, Career / Professional t...","All of the above, but they unfortunately fail ...","Tool for repetitive or menial tasks, Coding as...",Overuser / Devoted User (uses LLMs in most dom...,"Learning new skills, High-pressure deadlines, ...",(asking about athletic shirt details based on ...,...,4,4,2,4,ChatGPT,5,"Found it easier to prompt compared to Gemini, ...",Probably use AI,NaN,One example is when trying to improve image qu...
4,2/20/2026 14:20:33,Second-year transfer,Cognitive Science Design Spec,Never,NaN,"Environmental concerns, Ethical concerns, Conc...",General thinking assistant,AI skeptic (rarely or never uses LLMs),Actually useful tasks such as ML for cancer de...,Generating an image of a website low-fi wireframe,...,1,1,5,1,ChatGPT,1,Forced to by my professor as part of an assign...,Definitely not use AI,If the past three or so years of AI developmen...,Every single time

## Clean Majors Column

In [303]:
# Check for missing values in the majors column
survey_data['What is your major?'].isnull().sum()

# Ensure proper title case for the majors column, remove leading/trailing whitespace
survey_data['What is your major?'] = survey_data['What is your major?'].str.strip().str.title()

In [304]:
# Isolate the what is your major column for those that contain 'Design' 
design_majors = survey_data[survey_data['What is your major?'].str.contains('Design', case=False, na=False)]

#replace the major column with 'Cog Sci (Design)' for all the design majors
survey_data.loc[design_majors.index, 'What is your major?'] = 'Cog Sci (Design)'

In [305]:
#isolate the what is your major column for those that contain 'ML'
ml_majors = survey_data[survey_data['What is your major?'].str.contains('ML', case=False, na=False)]

#replace the major column with 'Cog Sci (ML)' for all the ml majors
survey_data.loc[ml_majors.index, 'What is your major?'] = 'Cog Sci (ML)'
survey_data.loc[ml_majors.index, 'What is your major?']

2     Cog Sci (ML)
26    Cog Sci (ML)
Name: What is your major?, dtype: object

In [306]:
survey_data['What is your major?'].unique()

array(['Esys', 'Data Science', 'Cog Sci (ML)', 'Icam/Cogsci',
       'Cog Sci (Design)', 'Cognitive Science', 'Medicine Sciences',
       'Software Engineering', 'Human Biology',
       'Decision Science (Economics)', 'Psych', 'Mechanical Engineering',
       'Computer Science', 'Math-Cs', 'Political Science',
       'Computer Engineering', 'Literature', 'Sociology',
       'Cognitive And Behavioral Neuroscience', 'English', 'Biology',
       'Social Sciences', 'Bioengineering', 'Gen Bio', 'Icam',
       'Public Health', 'Cse', 'Management Information Systems',
       'Marine Biology', 'Global Health B.S.', 'Business Psychology',
       'Icam & Data Science', 'Arts', 'Chemistry', 'Astrophysics',
       'Poli Sci And Business Econ', 'Chemical Engineering'], dtype=object)

In [307]:
# Isolate rows where college major contains '&' or 'and'
#double_majors = survey_data['What is your major?'].str.contains('&|and', case=False, na=False)

## EDA

### Simple Distributions

In [308]:
#plot the distribution of the 'How would you classify your AI-use persona' column
#clean column names by removing information in parentheses
survey_data['How would you classify your “AI-use personality”?'] = (
    survey_data['How would you classify your “AI-use personality”?']
    .str.split('(')
    .str[0]
    .str.strip()
)

#Reorder the values in the 'How would you classify your AI-use personality?' column by the number of responses for each category
personality_order = ["AI skeptic", "Cautious user", "Generous adopter", "Overuser / Devoted User"]
#cut out row where 'How would you classify your AI-use personality' contains Medium Use
survey_data_temp = survey_data[~survey_data['How would you classify your “AI-use personality”?'].str.contains('Medium Use', case=False, na=False)]

ai_personality_dist = px.histogram(survey_data_temp, 
                                   x='How would you classify your “AI-use personality”?', 
                                   title='Distribution of AI-Use Personalities', 
                                   width =800)

ai_personality_dist.update_layout( xaxis={'categoryorder':'array', 'categoryarray': personality_order})
ai_personality_dist.show()

In [309]:
#plot the distribution of 'In this situation, using AI felt like the most rational choice.' column
rational_choice_dist = px.histogram(survey_data, 
                                   x='In this situation, using AI felt like the most rational choice.', 
                                   title='Distribution of Rational Choice Responses', 
                                   
                                   width =800)
rational_choice_dist.update_layout(bargap=0.2)

#update plot to have a label indicating the average rationality score across all responses of 3.66
average_rationality = survey_data['In this situation, using AI felt like the most rational choice.'].mean()
rational_choice_dist.add_annotation(
    x=average_rationality,
    y=0,
    text=f'Average Rationality Score: {average_rationality:.2f}',
    showarrow=True,
    ax=0,
    ay=30
)
rational_choice_dist.show()

In [310]:
#find the average rationality score overall
average_rationality = survey_data['In this situation, using AI felt like the most rational choice.'].mean()
print(f'Average Rationality Score: {average_rationality:.2f}')

Average Rationality Score: 3.66

In [311]:
#plot box and whisker plot of 'How would you classify your AI-use personality?' column by 'In this situation, using AI felt like the most rational choice.' column
box_plot = px.box(survey_data,
                  x='How would you classify your “AI-use personality”?',
                  y='In this situation, using AI felt like the most rational choice.',
                  title='Rational Choice by AI-Use Personality',
                  width=1000,
                  height = 500)

box_plot.update_layout(xaxis_title='AI-Use Personality', yaxis_title='Rationality Score', xaxis={'categoryorder':'array', 'categoryarray': personality_order})

#label median values for each box and mean values for each box offset x value by 0.2 to the right and left respectively
for personality in personality_order:
    median_value = survey_data[survey_data['How would you classify your “AI-use personality”?'] == personality]['In this situation, using AI felt like the most rational choice.'].median()
    mean_value = survey_data[survey_data['How would you classify your “AI-use personality”?'] == personality]['In this situation, using AI felt like the most rational choice.'].mean()
    box_plot.add_annotation(x=personality, y=median_value, text=f'Median: {median_value:.2f}', showarrow=False, yshift=10, xshift= 100)
    box_plot.add_annotation(x=personality, y=mean_value, text=f'Mean: {mean_value:.2f}', showarrow=False, yshift= -10, xshift= 100)


box_plot.show()

In [312]:
survey_data.columns = survey_data.columns.str.strip()

In [313]:
#plot rational choice by How often do you use AI/LLM tools? 
survey_data_temp2 = survey_data[~survey_data['How often do you use AI/LLM tools?'].str.contains('Never', case=False, na=False)]
frequency_order = ['Never', 'A few times a year', 'About once a month', 'Once a week', 'Multiple times a week', 'Daily', 'Multiple times a day'   ]
box_plot_freq = px.box(survey_data_temp2,
                  x= 'How often do you use AI/LLM tools?',
                  y='In this situation, using AI felt like the most rational choice.',
                  title='Rational Choice by Frequency of AI Use',
                  width=1000,
                  height = 500)

box_plot_freq.update_layout(xaxis_title='Frequency of AI Use', yaxis_title='Rationality Score')
box_plot_freq.update_layout(xaxis={'categoryorder':'array', 'categoryarray': frequency_order})
box_plot_freq.show()

In [314]:
#generate a coding scheme for columns that have qualitative responses, eg. columns 12 through 19
survey_data.columns[12:]

Index(['How important was it to get an accurate response/output?',
       'If you had completed this task without using AI or LLM tools, how much effort do you think it would have required?',
       'Disregarding effort, how difficult would you describe the task to be?  (eg. How tedious is the task overall?)',
       'How much time pressure were you under? (e.g. close deadline, urgent response, or limited time to finish)',
       'What would have been the cost/consequence of making a mistake?',
       'Compared to doing it yourself, using AI felt:',
       'If AI had not been available, how likely is it that you would have completed the task at all?',
       'Using AI improved the quality of my final outcome.',
       'Using AI helped me think more clearly about the problem.',
       'Using AI required additional effort (e.g., prompting, correcting, fact-checking).',
       'In this situation, using AI felt like the most rational choice.',
       'What AI/LLM did you use? (please specify if other)',
       'Regarding your answer above, how familiar were you with the AI tool you used?',
       'Regarding the previous question, why did you choose to use this AI/LLM?',
       'If given the choice again for a similar task, I would:',
       'What conditions need to be present for you to feel confident that using AI is the “right” choice?',
       'Can you describe a time when using AI actually made the task harder or more time-consuming?'],
      dtype='object')

In [315]:
#rename columns 12 through 19 to be more concise
survey_data.columns[12:20]

survey_data.rename(columns={'How important was it to get an accurate response/output?': 'Importance of Accuracy',
       'If you had completed this task without using AI or LLM tools, how much effort do you think it would have required?': 'Task Effort (Without AI)',
       'Disregarding effort, how difficult would you describe the task to be?  (eg. How tedious is the task overall?)': 'Task Difficulty/Tedium',
       'How much time pressure were you under? (e.g. close deadline, urgent response, or limited time to finish)': 'Time Pressure',
       'What would have been the cost/consequence of making a mistake?': 'Consequence of Mistake',
       'In this situation, using AI felt like the most rational choice.': 'Rationality',
       'Compared to doing it yourself, using AI felt:': 'Speed of Output',
       'If AI had not been available, how likely is it that you would have completed the task at all?': 'Likelihood of Completion (w/o AI)',
       'Using AI improved the quality of my final outcome.': 'Quality Improved',
       'Regarding your answer above, how familiar were you with the AI tool you used?': 'Tool Familiarity',
       'Using AI helped me think more clearly about the problem.': 'Think More Clearly',
       'Using AI required additional effort (e.g., prompting, correcting, fact-checking).': 'Extra Effort Required (Using AI)',
       'If given the choice again for a similar task, I would:': 'Would Use AI Again'
}, inplace=True)

In [316]:
#create copy dataframe that groups by time pressure and averages rationality score for each time pressure level
time_pressure_rationality = survey_data.groupby('Time Pressure')['Rationality'].mean().reset_index()

#switch positions of first and last rows
time_pressure_rationality = time_pressure_rationality.iloc[[3, 1, 2, 0]]

In [317]:
#plot time pressure against average rationality using a line plot
time_pressure_rationality = px.line(time_pressure_rationality,
                                     x='Time Pressure',
                                     y='Rationality')
time_pressure_rationality.update_layout(title='Time Pressure vs. Rationality', xaxis_title='Time Pressure', yaxis_title='Rationality Score')
time_pressure_rationality.show()

In [318]:
#find column number for 'Rationality' column
survey_data.columns.get_loc('Rationality')

22

In [319]:
#check that the columns were renamed correctly
survey_data.iloc[:, 12:].head()

#create copy of dataframe for plotting correlations- include columns 12 through 22, as well as columns 24 and 26
part2_df = survey_data.iloc[:, [7] + list(range(12, 23)) + [24, 26]].copy()

#move rationality column to the beginning of the dataframe
# rationality_col = part2_df.pop('Rationality')
# part2_df.insert(0, 'Rationality', rationality_col)
part2_df.head()

,How would you classify your “AI-use personality”?,Importance of Accuracy,Task Effort (Without AI),Task Difficulty/Tedium,Time Pressure,Consequence of Mistake,Speed of Output,Likelihood of Completion (w/o AI),Quality Improved,Think More Clearly,Extra Effort Required (Using AI),Rationality,Tool Familiarity,Would Use AI Again
0,Cautious user,5,4,3,Moderate,No real consequence,Much faster,4,5,4,2,4,5,Probably use AI
1,Generous adopter,4,3,3,Moderate,Moderate impact,Much faster,5,4,5,5,5,5,Probably use AI
2,Generous adopter,4,3,2,Moderate,Moderate impact,Slightly faster,4,3,3,3,4,5,Unsure
3,Overuser / Devoted User,5,4,4,High,Moderate impact,Much faster,3,4,4,2,4,5,Probably use AI
4,AI skeptic,2,1,1,No time pressure,No real consequence,Much slower,5,1,1,5,1,1,Definitely not use AI

In [320]:
part2_df['Would Use AI Again'].isna().sum()

np.int64(0)

In [321]:
#create coding scheme for the categorical variables in part2_data for pearson correlation analysis
time_pressure_map = {
    "No time pressure": 1,
    "Minimal": 2,
    "Moderate": 3,
    "High": 4
}

consequence_map = {
    "No real consequence": 1,
    "Minor inconvenience": 2,
    "Moderate impact": 3,
    "High-stakes (grades, money, reputation, safety)": 4
}

speed_map = {
    "Much slower": 1,
    "Slightly slower": 2,
    "About the same": 3,
    "Slightly faster": 4,
    "Much faster": 5
}

would_use_ai_again_map = {
    "Definitely not use AI": 1,
    "Probably not use AI": 2,
    "Unsure": 3,
    "Probably use AI": 4,
    "Definitely use AI": 5
}

part2_df["Time Pressure"] = part2_df["Time Pressure"].map(time_pressure_map)
part2_df["Consequence of Mistake"] = part2_df["Consequence of Mistake"].map(consequence_map)
part2_df["Speed of Output"] = part2_df["Speed of Output"].map(speed_map)
part2_df["Would Use AI Again"] = part2_df["Would Use AI Again"].map(would_use_ai_again_map)
part2_df["Would Use AI Again"] = part2_df["Would Use AI Again"].astype("Int64")
part2_df.head()

,How would you classify your “AI-use personality”?,Importance of Accuracy,Task Effort (Without AI),Task Difficulty/Tedium,Time Pressure,Consequence of Mistake,Speed of Output,Likelihood of Completion (w/o AI),Quality Improved,Think More Clearly,Extra Effort Required (Using AI),Rationality,Tool Familiarity,Would Use AI Again
0,Cautious user,5,4,3,3,1,5,4,5,4,2,4,5,4
1,Generous adopter,4,3,3,3,3,5,5,4,5,5,5,5,4
2,Generous adopter,4,3,2,3,3,4,4,3,3,3,4,5,3
3,Overuser / Devoted User,5,4,4,4,3,5,3,4,4,2,4,5,4
4,AI skeptic,2,1,1,1,1,1,5,1,1,5,1,1,1

In [322]:
part2_df.head()

,How would you classify your “AI-use personality”?,Importance of Accuracy,Task Effort (Without AI),Task Difficulty/Tedium,Time Pressure,Consequence of Mistake,Speed of Output,Likelihood of Completion (w/o AI),Quality Improved,Think More Clearly,Extra Effort Required (Using AI),Rationality,Tool Familiarity,Would Use AI Again
0,Cautious user,5,4,3,3,1,5,4,5,4,2,4,5,4
1,Generous adopter,4,3,3,3,3,5,5,4,5,5,5,5,4
2,Generous adopter,4,3,2,3,3,4,4,3,3,3,4,5,3
3,Overuser / Devoted User,5,4,4,4,3,5,3,4,4,2,4,5,4
4,AI skeptic,2,1,1,1,1,1,5,1,1,5,1,1,1

In [323]:
part2_df.dtypes

#find the location of any non-numeric values in part2_df
mask = part2_df.applymap(lambda x: not isinstance(x, (int, float)) and pd.notnull(x))

locations = mask.stack()
locations = locations[locations]

locations

/var/folders/sy/4l4dyg_s0957ygcxs_nz9spm0000gp/T/ipykernel_88392/2603999433.py:4: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  mask = part2_df.applymap(lambda x: not isinstance(x, (int, float)) and pd.notnull(x))

0   How would you classify your “AI-use personality”?    True
1   How would you classify your “AI-use personality”?    True
2   How would you classify your “AI-use personality”?    True
3   How would you classify your “AI-use personality”?    True
4   How would you classify your “AI-use personality”?    True
                                                         ...
60  How would you classify your “AI-use personality”?    True
61  How would you classify your “AI-use personality”?    True
62  How would you classify your “AI-use personality”?    True
63  How would you classify your “AI-use personality”?    True
64  How would you classify your “AI-use personality”?    True
Length: 65, dtype: bool

In [324]:
#export part2_df to csv file
part2_df.to_csv('/Users/nicolechen/COGS 180/part2_df_2.csv', index=False)

In [325]:
part2_df.iloc[1]

How would you classify your “AI-use personality”?    Generous adopter
Importance of Accuracy                                              4
Task Effort (Without AI)                                            3
Task Difficulty/Tedium                                              3
Time Pressure                                                       3
Consequence of Mistake                                              3
Speed of Output                                                     5
Likelihood of Completion (w/o AI)                                   5
Quality Improved                                                    4
Think More Clearly                                                  5
Extra Effort Required (Using AI)                                    5
Rationality                                                         5
Tool Familiarity                                                    5
Would Use AI Again                                                  4
Name: 1, dtype: object

### Top Parameters by Spearman Correlation Per AI Personality Type

In [326]:
#write function to filter part2_df by each of the 4 personality types and calculate spearman correlation values with rationality for each personality type
def calculate_correlations_by_personality(df, personality):
    filtered_df = df[df['How would you classify your “AI-use personality”?'] == personality]
    filtered_df = filtered_df.drop(columns=['How would you classify your “AI-use personality”?'])
    correlation_matrix = filtered_df.corr(method='spearman')
    return correlation_matrix['Rationality'].sort_values(ascending=False)

corr_generous = calculate_correlations_by_personality(part2_df, 'Generous adopter')

In [327]:
#plot the distribution of 'In this situation, using AI felt like the most rational choice.' column by AI-use personality as a barplot for the top 4 most positively correlated variables with rationality for each personality type
#drop rationality from the correlation series
#corr_generous = corr_generous.drop('Rationality')

#sort the correlation values in descending order and take the top 4 most positively correlated variables with rationality

import plotly.graph_objects as go
import plotly.express as px

def create_corr_bar_plot(corr_series, personality):

    corr_series = corr_series.drop('Rationality')
    corr_series = corr_series.sort_values(ascending=False).head(5)

    colors = px.colors.sample_colorscale(
        px.colors.sequential.BuPu,
        [i/(len(corr_series)-1) for i in range(len(corr_series))]
    )

    fig = go.Figure()

    fig.add_bar(
        x=corr_series.values,
        y=corr_series.index[::-1],
        orientation='h',
        marker=dict(color=colors),
        text=corr_series.values.round(3),
        textposition='outside'
    )

    fig.update_yaxes(
    ticks="outside",
    ticklen=10,
    tickwidth=1,
    tickcolor='white',
   
)

    return fig
create_corr_bar_plot(corr_generous, 'Generous adopter')

In [328]:
corr_overuser =calculate_correlations_by_personality(part2_df, 'Overuser / Devoted User')
create_corr_bar_plot(corr_overuser, 'Overuser / Devoted User')

In [329]:
corr_cautious = calculate_correlations_by_personality(part2_df, 'Cautious user')
create_corr_bar_plot(corr_cautious, 'Cautious user')

In [330]:
corr_skeptic = calculate_correlations_by_personality(part2_df, 'AI skeptic')
create_corr_bar_plot(corr_skeptic, 'AI skeptic')

In [332]:
from plotly.subplots import make_subplots

fig = make_subplots(rows=1, cols=4, shared_yaxes=False, horizontal_spacing=0.1, subplot_titles=[
        "Cautious user",
        "Generous adopter",
        "Overuser / Devoted User"
    ])
fig.add_traces(create_corr_bar_plot(corr_cautious, "Cautious user").data, rows=1, cols=1)
fig.add_traces(create_corr_bar_plot(corr_generous, "Generous adopter").data, rows=1, cols=2)
fig.add_traces(create_corr_bar_plot(corr_overuser, "Overuser / Devoted User").data, rows=1, cols=3)

#adjust subplot titles, x-axis titles, and y-axis titles, and width of the plot
fig.update_layout(
    title_text="Top 5 Correlated Variables with Rationality by AI-Use Personality",
    title_x=0.42,
    height=600,
    width=1600,
    
    showlegend=False
)

fig.update_yaxes(
    ticks="outside",
    ticklen=10,
    tickwidth=1,
    tickcolor='white',
   
)

#change dimensions of individual subplots to make them wider
fig.update_xaxes(range=[0, 1], row=1, col=1)
fig.update_xaxes(range=[0, 1], row=1, col=2)
fig.update_xaxes(range=[0, 1], row=1, col=3)
fig.show()

In [235]:
part2_df.drop(columns=['How would you classify your “AI-use personality”?'], inplace=True)

In [236]:
#find correlation matrix for part2_df between rationality column and the other columns
correlation_matrix = part2_df.corr(method='spearman')
correlation_matrix['Rationality'].sort_values(ascending=False)

Rationality                              1.000000
Would Use AI Again                       0.483470
Task Difficulty/Tedium                   0.471907
Quality Improved                         0.305375
Tool Familiarity                         0.283944
Task Effort (Without AI)                 0.180816
Think More Clearly                       0.180348
Importance of Accuracy                   0.138777
Speed of Output                          0.134994
Extra Effort Required (Using AI)         0.069768
Consequence of Mistake                   0.033253
Time Pressure                           -0.077687
Likelihood of Completion (without AI)   -0.129388
Name: Rationality, dtype: float64

In [237]:
#plot correlation matrix as a horizontal barplot using plotly express and the BuPu color scale
rationality_corr = (
    correlation_matrix["Rationality"]
    .drop("Rationality")
    .sort_values(ascending=False)
)

fig = px.bar(
    x=rationality_corr.values,
    y=rationality_corr.index,
    labels={"x": "Spearman Correlation", "y": "Variable"},
    title="Correlation with Rationality",
    orientation = 'h',
    color=rationality_corr.values,
    color_continuous_scale=px.colors.sequential.BuPu,
    text = rationality_corr.values.round(3),
    width = 1100, 
)

fig.update_layout(
    margin=dict(
        l=150))

fig.update_yaxes(
    ticks="outside",
    ticklen=10,
    tickwidth=1,
    tickcolor='white',
   
)
fig.show()

In [246]:
#plot correlation matrix of top 4 variables that are most positively correlated with rationality as a heatmap against rationality scores using plotly express and the BuPu color scale

top4_corr = rationality_corr.head(4).index.tolist() + ['Rationality']
heatmap_data = part2_df[top4_corr] 
heatmap_data = heatmap_data.corr(method='spearman')
heatmap_data = heatmap_data.round(2)

fig = px.imshow(
    heatmap_data,
    x=heatmap_data.columns,
    y=heatmap_data.index,
    color_continuous_scale=px.colors.sequential.BuPu,
    title="Correlation Heatmap of Top 4 Variables Correlated with Rationality",
    text_auto=True,
    width = 700, 
    height = 700
)
fig.show()

# #update heatmap with p values for the correlations and mask non-significant correlations with a different color (e.g. grey) using plotly express and the BuPu color scale
# # calculate p values for the correlations using scipy spearmanr function
# from scipy.stats import spearmanr
# corr, pvals = spearmanr(top4_corr)

# cols1 = top4_corr.columns

# spearman_corr = pd.DataFrame(corr, index=cols, columns=cols)
# pval_matrix = pd.DataFrame(pvals, index=cols, columns=cols)

# # significance threshold
# alpha = 0.05

# # keep only statistically significant correlations
# significant_corr = spearman_corr.where(pval_matrix < alpha)

In [99]:
from scipy.stats import spearmanr
corr, pvals = spearmanr(part2_df)

cols = part2_df.columns

spearman_corr = pd.DataFrame(corr, index=cols, columns=cols)
pval_matrix = pd.DataFrame(pvals, index=cols, columns=cols)

# significance threshold
alpha = 0.05

# keep only statistically significant correlations
significant_corr = spearman_corr.where(pval_matrix < alpha)

In [ ]:
#plot significant_corr as a heatmap using plotly express
significant_heatmap = px.imshow(
    significant_corr,
    labels={"x": "Variable", "y": "Variable", "color": "Spearman Correlation"},
    x=significant_corr.columns,
    y=significant_corr.columns,
    color_continuous_scale=px.colors.sequential.BuPu,
    title="Significant Correlations Heatmap",
    width = 1000,
    height = 1000
)
significant_heatmap.show()

In [98]:
#plot p values as a heatmap using plotly express 
pval_heatmap = px.imshow(
    pval_matrix,
    labels={"x": "Variable", "y": "Variable", "color": "P-value"},
    x=pval_matrix.columns,
    y=pval_matrix.columns,
    color_continuous_scale=px.colors.sequential.BuPu,
    title="P-values Heatmap",
    width = 800,
    height = 800
)
pval_heatmap.show()